@startuml diagramaClase

class ListaTareas {
    - tareas: List<Tarea>
    - ordenador: Ordenamiento
    - buscador: Busqueda
    + getLista(): List<Tarea>
    + agregarTarea(tarea: Tarea)
    + eliminarTarea(tarea: Tarea)
    + getPendientes(): List<Tarea>
    + getCompletadas(): List<Tarea>
    - calcularTiempoPromedio()
    + calcularEstadisticas()
}

class Tarea {
    - titulo: String
    - descripcion: String
    - fechaCreacion: Date
    - fechaVencimiento: Date
    - prioridad: Prioridad
    - etiquetas: List<String>
    - categoria: Categoria
    - progreso: int
    - completada: boolean
    + marcarCompletada()
    + agregarEtiqueta(etiqueta: String)
    + editar()
}

interface Busqueda {
    + buscar(): List<Tarea>
}

interface Ordenamiento {
    + ordenar()
}

class BuscadorTitulo implements Busqueda {
    + buscar(titulo: String): List<Tarea>
}

class BuscadorFecha implements Busqueda {
    + buscar(fecha: Date): List<Tarea>
}

class OrdenadorTitulo implements Ordenamiento {
    + ordenar()
}

class OrdenadorFecha implements Ordenamiento {
    + ordenar()
}

class OrdenadorPrioridad implements Ordenamiento {
    + ordenar()
}

enum Prioridad {
    ALTA
    MEDIA
    BAJA
}

enum Categoria {
    TRABAJO
    PERSONAL
    RECADOS
}

ListaTareas "1" *-- "*" Tarea
ListaTareas *-- Busqueda
ListaTareas *-- Ordenamiento

@enduml